apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: dynatrace
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://raw.githubusercontent.com/martinnirtl/helm-charts/master/charts
    chart: dynatrace-operator
    targetRevision: 0.6.0
  syncPolicy:
    automated: {}

