apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name | default .Release.Name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server | default "https://kubernetes.default.svc" }}
    namespace: dynatrace
  project: {{ .Values.spec.project | default "default" }}
  source:
    repoURL: https://raw.githubusercontent.com/martinnirtl/helm-charts/master/charts
    chart: dynatrace-operator
    targetRevision: 0.6.0

